//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Metadataclasses.EmployeeMetadata))]
    public partial class Employee
    {
        public Employee()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Address { get; set; }
        public string IqmaNumber { get; set; }
        public string SalaryType { get; set; }
    
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
