//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities1 : DbContext
    {
        public DbEntities1()
            : base("name=DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comodity> Comodities { get; set; }
        public virtual DbSet<Consignee> Consignees { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Packing> Packings { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceForQuotation> ServiceForQuotations { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
