//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Metadataclasses.ServiceMetadata))]
    public partial class Service
    {
        public Service()
        {
            this.ServiceForQuotations = new HashSet<ServiceForQuotation>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ServiceForQuotation> ServiceForQuotations { get; set; }
    }
}
